In [1]:
import numpy as np
import MinCompSpin as mod

# Test 1: Read data 128 bits

In [2]:
datafile = "./INPUT/SCOTUS_n9_N895_Data.dat"
N=0
n=9

In [11]:
data=mod.read_datafile(datafile, n)
type(data)

Read the dataset: ./INPUT/SCOTUS_n9_N895_Data.dat
Number of variables to read: n = 9


MinCompSpin.Kset

In [12]:
data.array

array([[  0,   0, 174],
       [  1,   0,   2],
       [  4,   0,   8],
       [ 16,   0,   2],
       [ 20,   0,   1],
       [ 32,   0,   3],
       [ 33,   0,   1],
       [ 36,   0,  29],
       [ 44,   0,   1],
       [ 52,   0,   9],
       [ 64,   0,   1],
       [ 65,   0,   1],
       [ 67,   0,   1],
       [ 68,   0,   1],
       [ 75,   0,   1],
       [ 76,   0,   1],
       [ 82,   0,   1],
       [100,   0,   8],
       [111,   0,   1],
       [116,   0,   2],
       [128,   0,   1],
       [129,   0,   3],
       [130,   0,   2],
       [132,   0,   1],
       [133,   0,   1],
       [139,   0,   3],
       [142,   0,   1],
       [160,   0,   1],
       [164,   0,   1],
       [166,   0,   1],
       [171,   0,   1],
       [172,   0,   1],
       [175,   0,   1],
       [176,   0,   1],
       [180,   0,   1],
       [195,   0,   1],
       [203,   0,   1],
       [211,   0,   1],
       [213,   0,   1],
       [217,   0,   1],
       [221,   0,   1],
       [231,   0

In [6]:
## Maybe "Entropy" could be a methods under Kset?
mod.Entropy(data)

4.411845516595921

# Test: Run Greedy Algo:

In [13]:
MCM_best = mod.MCM_GreedySearch(data, n, True)
type(MCM_best)

	 **** Filling in the rxr-triangular Matrix ****
	 **** Start Merging ****
	 Done with iteration 1
	 Done with iteration 2
	 Done with iteration 3
	 Done with iteration 4
	 Done with iteration 5
	 Done with iteration 6
	 Done with iteration 7
	 **** Greedy Merging Finished ****



Element [0] = 0
freeing memory @ 0x6000002f85a0


MinCompSpin.Partitions

In [16]:
MCM_best.r

9

In [17]:
MCM_best.array

array([[  0, 139,   0],
       [  2, 372,   0]], dtype=uint64)

In [18]:
MCM_best2=mod.MCM_GreedySearch_AND_printInfo(data, n, True)

######### START GREEDY SEARCH #########
	 **** Filling in the rxr-triangular Matrix ****
	 **** Start Merging ****
	 Done with iteration 1
	 Done with iteration 2
	 Done with iteration 3
	 Done with iteration 4
	 Done with iteration 5
	 Done with iteration 6
	 Done with iteration 7
	 **** Greedy Merging Finished ****

Run time : 0.000377s

######### ENTROPY OF THE DATA #########
S = 4.41185 bits. Range: [0, 9]

#########  GREEDY: BEST MCM FOUND:   #########
ICC 1: 	 010001011
ICC 2: 	 101110100

Log-Evidence(MCM)       : -3300.4	 = -5.32007 bits per datapoint 	
Max-Log-Likelihood(MCM) : -3194.36	 = -5.14915 bits per datapoint 	

Average community size  : 4.5 variables per community 	



In [14]:
type(MCM_best2)

MinCompSpin.Partitions

In [15]:
MCM_best2.array

array([[  0, 139,   0],
       [  2, 372,   0]], dtype=uint64)

# Test: Other functionalities:

For the following function: "MCM_best.r" shouldn't be needed as it is already one attribute of "Partitions":

In [16]:
mod.LogE_MCM(data, MCM_best, MCM_best.r)

-3300.395469673638

In [17]:
mod.LogE_MCM_infoICC(data, MCM_best, MCM_best.r)

Complete model: 111111111	  LogE(CM) = -3305.547	 = -5.328 bits per datapoint

ICC 1: 	 010001011	 LogE(ICC) = -1545.984	 = -2.492 bits per datapoint 	
ICC 2: 	 101110100	 LogE(ICC) = -1754.412	 = -2.828 bits per datapoint 	

Log-Evidence(MCM) = -3300.395	 = -5.320 bits per datapoint 	


-3300.395469673638

In [19]:
mod.LogL_MCM(data, MCM_best, MCM_best.r)

-3194.3593638660923

In [21]:
mod.Print_MCM_Partition(MCM_best, MCM_best.r)

ICC 1: 	 010001011
ICC 2: 	 101110100



# Test: Define a new MCM:

In [23]:
new_part = np.array([[  0, 139,   0], [  2, 372,   0]], dtype=int)

In [21]:
new_part

array([[  0, 139,   0],
       [  2, 372,   0]])

In [24]:
new_MCM = mod.Partitions(new_part, 9)

In [25]:
type(new_MCM)

MinCompSpin.Partitions

In [27]:
new_MCM.array

array([[  0, 139,   0],
       [  2, 372,   0]], dtype=uint64)

In [23]:
mod.LogE_MCM_infoICC(data, new_MCM, 9)

Complete model: 111111111	  LogE(CM) = -3305.547	 = -5.328 bits per datapoint

ICC 1: 	 010001011	 LogE(ICC) = -1545.984	 = -2.492 bits per datapoint 	
ICC 2: 	 101110100	 LogE(ICC) = -1754.412	 = -2.828 bits per datapoint 	

Log-Evidence(MCM) = -3300.395	 = -5.320 bits per datapoint 	


-3300.395469673638

# Test: getting a binary string from a "part" or a "state":

In [24]:
print(bin(139))
print(bin(372))

0b10001011
0b101110100


In [28]:
# Removing the leading characters:
x = 139
binary = bin(x)
stripped_binary = binary.lstrip('-0b')
print(stripped_binary)

10001011


In [58]:
# Enforcing a fixed number of digits (ex. 9 here)
x = 139
binary = bin(x)[2:].zfill(9)
print(binary)

010001011


In [66]:
test=list(binary)
test

['0', '1', '0', '0', '0', '1', '0', '1', '1']

In [67]:
t=np.array(test, dtype = int)
t

array([0, 1, 0, 0, 0, 1, 0, 1, 1])

In [57]:
t==1

array([False,  True, False, False, False,  True, False,  True,  True])

In [65]:
np.array(list(binary), dtype=int)

array([0, 1, 0, 0, 0, 1, 0, 1, 1])